# Generated by Django 5.1.3 on 2024-11-26 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tyj', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tyj',
            old_name='fio',
            new_name='shartli_nom',
        ),
        migrations.RemoveField(
            model_name='tyj',
            name='jshshir',
        ),
    ]
