# Generated by Django 5.1.3 on 2024-11-29 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tyj', '0002_rename_fio_tyj_shartli_nom_remove_tyj_jshshir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tyj',
            old_name='tyjn',
            new_name='tyj_N',
        ),
    ]
