# Generated by Django 5.1.3 on 2024-11-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, null=True)),
                ('number', models.CharField(max_length=100, null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('boshqarma', models.CharField(max_length=100, null=True)),
                ('lavozim', models.CharField(max_length=100, null=True)),
                ('unvon', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
