# Generated by Django 5.1.3 on 2024-11-26 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_user_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pin',
        ),
    ]
