# Generated by Django 5.1.3 on 2024-11-29 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jinoyat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jinoyat',
            old_name='jinoyatn',
            new_name='jinoyat_N',
        ),
    ]
