# Generated by Django 5.1.3 on 2024-11-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArizaDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=15, null=True)),
                ('number', models.CharField(max_length=15, null=True)),
                ('model', models.CharField(max_length=100, null=True)),
                ('color', models.CharField(max_length=100, null=True)),
                ('info', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
